//Given two strings s and t which consist of only lowercase letters.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Find the letter that was added in t.
//
//Example:
//
//Input:
//s = "abcd"
//t = "abcde"
//
//Output:
//e
//
//Explanation:
//'e' is the letter that was added.

package wenxinjie4;

public class leetcode389_Find_the_Difference {
    public char findTheDifference(String s, String t) {
        int n = s.length();
        char c = t.charAt(n);
        
        for (int i = 0; i < n; i ++){
            c ^= s.charAt(i);
            c ^= t.charAt(i);
        }
        return c;
    }	
}

//Time: O(n)
//Space: O(1)
//Difficulty: easy