# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

# Example:

# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        a,b = map(collections.Counter, (s,t))
        # print(a,b)
        b.subtract(a)
        return list(b.elements())[0]

# Time: O(n)
# Space: O(n)
# Difficulty: easy